apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: ancela/cast-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: SERVICE_NAME
          value: "cast-service"
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: dev
spec:
  selector:
    app: cast-service
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
